version: "3.9"

services:
  api:
    image: encrypted-file-storage-api
    restart: always
    volumes:
      - ./data:/app/data
    expose:
      - 5000
    command: ["/app/out"]

  web:
    image: encrypted-file-storage-web
    restart: always
    expose:
      - 3000
    command: ["npm", "run", "start"]

  reverse-proxy:
    image: nginx
    depends_on:
      - api
      - web
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/ssl/certs
    ports:
      - 443:443
