version: "3.9"

services:
  api:
    restart: always
    build:
      context: ./apps/api
      dockerfile: Dockerfile.dev
    expose:
      - 3000
    volumes:
      - ./apps/api:/go/src/app
    command: ["air"]

  web:
    restart: always
    build:
      context: ./apps/web
      dockerfile: Dockerfile.dev
    expose:
      - 3000
    volumes:
      - ./apps/web:/app
    command: ["npm", "run", "dev"]

  reverse-proxy:
    image: nginx
    depends_on:
      - api
      - web
    restart: always
    volumes:
      - ./nginx/dev.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/ssl/certs
    ports:
      - 80:80
      - 443:443
