version: "3.9"

services:
  api:
    restart: always
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    expose:
      - 80

  web:
    restart: always
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    expose:
      - 80

  reverse-proxy:
    image: nginx
    depends_on:
      - api
      - web
    restart: always
    volumes:
      - ./nginx/prod.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/ssl/certs
    ports:
      - 443:443
